/// Flutter icons ElectroluxIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ElectroluxIcons
///      fonts:
///       - asset: fonts/ElectroluxIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ElectroluxIcons {
  ElectroluxIcons._();

  static const _kFontFam = 'ElectroluxIcons';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData alert = const IconData(0xe900, fontFamily: _kFontFam);
  static const IconData alert_status = const IconData(0xe901, fontFamily: _kFontFam);
  static const IconData app_setting = const IconData(0xe902, fontFamily: _kFontFam);
  static const IconData appliances = const IconData(0xe903, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe904, fontFamily: _kFontFam);
  static const IconData arrow_drop_down = const IconData(0xe905, fontFamily: _kFontFam);
  static const IconData arrow_drop_up = const IconData(0xe906, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe907, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe908, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe909, fontFamily: _kFontFam);
  static const IconData blast = const IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData calendar_1_days = const IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData calendar_7_days = const IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData calendar_30_days = const IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData category = const IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData check_box_checked = const IconData(0xe910, fontFamily: _kFontFam);
  static const IconData check_box_unchecked = const IconData(0xe911, fontFamily: _kFontFam);
  static const IconData chill = const IconData(0xe912, fontFamily: _kFontFam);
  static const IconData chilling_mode = const IconData(0xe913, fontFamily: _kFontFam);
  static const IconData cleaning = const IconData(0xe914, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe915, fontFamily: _kFontFam);
  static const IconData combi = const IconData(0xe916, fontFamily: _kFontFam);
  static const IconData convection = const IconData(0xe917, fontFamily: _kFontFam);
  static const IconData cooking_mode = const IconData(0xe918, fontFamily: _kFontFam);
  static const IconData dashboard = const IconData(0xe919, fontFamily: _kFontFam);
  static const IconData date_format = const IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData delay = const IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData dishwasher = const IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData down_plate = const IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData duplicate = const IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData duplicate_v2 = const IconData(0xe920, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe921, fontFamily: _kFontFam);
  static const IconData fan_speed = const IconData(0xe922, fontFamily: _kFontFam);
  static const IconData first_week_day = const IconData(0xe923, fontFamily: _kFontFam);
  static const IconData food_save_control = const IconData(0xe924, fontFamily: _kFontFam);
  static const IconData fridge = const IconData(0xe925, fontFamily: _kFontFam);
  static const IconData frozen = const IconData(0xe926, fontFamily: _kFontFam);
  static const IconData guideline_k = const IconData(0xe927, fontFamily: _kFontFam);
  static const IconData guideline_manual = const IconData(0xe928, fontFamily: _kFontFam);
  static const IconData guideline_ns = const IconData(0xe929, fontFamily: _kFontFam);
  static const IconData guideline_snf = const IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData haccp = const IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData half_power = const IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData hold = const IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData hold_add = const IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData hour_format = const IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData humidity = const IconData(0xe930, fontFamily: _kFontFam);
  static const IconData hygen = const IconData(0xe931, fontFamily: _kFontFam);
  static const IconData iron = const IconData(0xe932, fontFamily: _kFontFam);
  static const IconData language = const IconData(0xe933, fontFamily: _kFontFam);
  static const IconData laundry = const IconData(0xe934, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe935, fontFamily: _kFontFam);
  static const IconData locator = const IconData(0xe936, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe937, fontFamily: _kFontFam);
  static const IconData measure = const IconData(0xe938, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe939, fontFamily: _kFontFam);
  static const IconData messages = const IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData metric = const IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData microwave = const IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData multiphase = const IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData multiphase_v2 = const IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData options = const IconData(0xe940, fontFamily: _kFontFam);
  static const IconData oven = const IconData(0xe941, fontFamily: _kFontFam);
  static const IconData oven_precooling = const IconData(0xe942, fontFamily: _kFontFam);
  static const IconData overview = const IconData(0xe943, fontFamily: _kFontFam);
  static const IconData parameters = const IconData(0xe944, fontFamily: _kFontFam);
  static const IconData password_invisibile = const IconData(0xe945, fontFamily: _kFontFam);
  static const IconData password_visibile = const IconData(0xe946, fontFamily: _kFontFam);
  static const IconData pause = const IconData(0xe947, fontFamily: _kFontFam);
  static const IconData pause_add = const IconData(0xe948, fontFamily: _kFontFam);
  static const IconData permissions = const IconData(0xe949, fontFamily: _kFontFam);
  static const IconData phase_add = const IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData pressure = const IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData probe = const IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData program = const IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData program_management = const IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData programs = const IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData radio_button_checked = const IconData(0xe950, fontFamily: _kFontFam);
  static const IconData radio_button_unchecked = const IconData(0xe951, fontFamily: _kFontFam);
  static const IconData recipes_management = const IconData(0xe952, fontFamily: _kFontFam);
  static const IconData save_program = const IconData(0xe953, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe954, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe955, fontFamily: _kFontFam);
  static const IconData smoker = const IconData(0xe956, fontFamily: _kFontFam);
  static const IconData sort_none = const IconData(0xe957, fontFamily: _kFontFam);
  static const IconData speedelight = const IconData(0xe958, fontFamily: _kFontFam);
  static const IconData speedelight_off = const IconData(0xe959, fontFamily: _kFontFam);
  static const IconData speedelight_preheating = const IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData speedelight_programs = const IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData speedelight_programs_01 = const IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData speedelight_programs_02 = const IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData speedelight_programs_03 = const IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData speedelight_programs_04 = const IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData speedelight_programs_05 = const IconData(0xe960, fontFamily: _kFontFam);
  static const IconData speedelight_programs_06 = const IconData(0xe961, fontFamily: _kFontFam);
  static const IconData speedelight_programs_07 = const IconData(0xe962, fontFamily: _kFontFam);
  static const IconData speedelight_programs_08 = const IconData(0xe963, fontFamily: _kFontFam);
  static const IconData speedelight_ready = const IconData(0xe964, fontFamily: _kFontFam);
  static const IconData speedelight_stand_by = const IconData(0xe965, fontFamily: _kFontFam);
  static const IconData statistics = const IconData(0xe966, fontFamily: _kFontFam);
  static const IconData steam = const IconData(0xe967, fontFamily: _kFontFam);
  static const IconData tavola_disegno = const IconData(0xe968, fontFamily: _kFontFam);
  static const IconData temperature = const IconData(0xe969, fontFamily: _kFontFam);
  static const IconData tick = const IconData(0xe96a, fontFamily: _kFontFam);
  static const IconData time_zone = const IconData(0xe96b, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe96c, fontFamily: _kFontFam);
  static const IconData upperplate = const IconData(0xe96d, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe96e, fontFamily: _kFontFam);
  static const IconData user_management = const IconData(0xe96f, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe970, fontFamily: _kFontFam);
  static const IconData water_injection = const IconData(0xe971, fontFamily: _kFontFam);
  static const IconData x_freeze = const IconData(0xe972, fontFamily: _kFontFam);
}
